# Generated by Django 4.2.6 on 2023-12-13 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.IntegerField()),
                ('sector', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('insight', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('region', models.CharField(max_length=100)),
                ('impact', models.CharField(blank=True, max_length=100, null=True)),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('published', models.DateTimeField()),
                ('country', models.CharField(max_length=100)),
                ('relevance', models.IntegerField()),
                ('pestle', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('likelihood', models.IntegerField()),
                ('start_year', models.IntegerField(null=True)),
                ('end_year', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
